### ISSUE TITLE
USER STORY: Ability to add a comment before submitting my poll response

### ISSUE THREAD

**Issue by seunajetomobi** [gullah26/My-First-Agile-Project#3]
In order to **air my opinion** as a **user**, I can **add a comment before submitting my poll response**.

## Acceptance Criteria:

* The comment section should accommodate nothing less than 500 words.
* The comment font should be italic by default.
* the submit button should be directly after the comment environment.
* After submission there should be a submit confirmation message, saying thank you for your comment or feedback.

## Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Option for anonymity
- [ ] The comment section pane of 500 words
